namespace JobTrack.Host.Config;

/// <summary>
/// Every path the host cares about, in one place.
/// </summary>
/// <remarks>
/// The split between the two roots is deliberate and matches what the npm package already does.
/// The install directory is disposable — an uninstall deletes it wholesale — while
/// <see cref="JobtrackHome"/> is the user's data and must survive uninstalling, reinstalling, and
/// switching between the installer and <c>npm install -g jobtrack</c>. It resolves to the same
/// <c>%APPDATA%\jobtrack</c> that <c>apps/tray/bin/jobtrack.js</c> defaults to, so the two
/// channels share one database rather than silently keeping two.
/// </remarks>
internal static class Paths
{
    /// <summary>Where JobTrack.exe and the Node payload live.</summary>
    public static string InstallDir { get; } = AppContext.BaseDirectory.TrimEnd(Path.DirectorySeparatorChar);

    /// <summary>The app data directory the server is told to use, via its <c>--home</c> flag.</summary>
    public static string JobtrackHome { get; } =
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "jobtrack");

    public static string EnvFile => Path.Combine(JobtrackHome, ".env");

    public static string DataDir => Path.Combine(JobtrackHome, "data");

    /// <summary>The token the browser extension needs; generated by the server on first run.</summary>
    public static string ApiTokenFile => Path.Combine(DataDir, "api-token");

    public static string LaunchManifestFile => Path.Combine(InstallDir, "app", "launch.json");

    /// <summary>
    /// Logs go under LOCALAPPDATA rather than beside the database: they are ours, not the user's,
    /// they are deleted on uninstall without asking, and on a roaming profile they have no
    /// business being synced.
    /// </summary>
    public static string LogDir { get; } = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "JobTrack", "logs");

    public static string HostSettingsFile => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "JobTrack", "host.json");

    public static string Resolve(string installRelative) => Path.GetFullPath(Path.Combine(InstallDir, installRelative));

    public static void EnsureDataDirectories()
    {
        Directory.CreateDirectory(JobtrackHome);
        Directory.CreateDirectory(LogDir);
    }
}
